version: '3.8'

services:  
  mysql:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_USER: panorama
      MYSQL_ROOT_PASSWORD: panorama-root
      MYSQL_PASSWORD: panorama
      MYSQL_DATABASE: panorama-db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

volumes:
  mysql-data:

