version: '3.8'

services:  
  mysql:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_USER: panorama
      MYSQL_ROOT_PASSWORD: panorama-root
      MYSQL_PASSWORD: panorama
      MYSQL_DATABASE: panorama-db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
  app:
    build: .
    ports:
        - 3000:3000
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=panorama_db
      - DATABASE_USER=panorama
      - DATABASE_PASSWORD=panorama
    depends_on:
      - mysql

volumes:
  mysql-data: