version: '3.8'

services:  
  mysql:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: panorama
      MYSQL_ROOT_PASSWORD: panorama-root
      MYSQL_PASSWORD: panorama
      MYSQL_DATABASE: panorama-db
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

